# Generated by Django 5.2.9 on 2025-12-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('provider', models.CharField(max_length=128, verbose_name='Provider')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Exchange rate provider configuration',
                'verbose_name_plural': "Exchange rate providers' configurations",
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'indexes': [models.Index(fields=['code'], name='core_curren_code_fcefac_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('rate_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exchanged_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='core.currency')),
            ],
            options={
                'verbose_name': 'Currency exchange rate',
                'verbose_name_plural': 'Currency exchange rates',
                'constraints': [models.UniqueConstraint(fields=('source_currency', 'exchanged_currency', 'valuation_date'), name='unique_currency_pair_date')],
            },
        ),
    ]
